import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './global.css';
import ThemeRegistry from './ThemeRegistry';
import { Header } from '@/components/Header';
import { logo } from '@/utils/contants';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'YouTube Clone',
  description: 'Generated by create next app',
  icons: [{ url: logo }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
